from typing import Callable

def remove_extra_whitespace(s: str) -> str: ...
def custom_sent_tokenize(text: str) -> list[str]: ...
def create_chunks(
    text: str, chunk_size: int, length_fn: Callable[[str], int]
) -> list[str]: ...
