from typing import Any, Iterator

def is_valid_json(json_str: str) -> bool: ...
def flatten(nested_list) -> Iterator[str]: ...
def get_json_candidates(s: str) -> list[str]: ...
def add_quotes(s: str) -> str: ...
def repair_newlines(s: str) -> str: ...
def extract_top_level_json(s: str) -> list[str]: ...
def top_level_json_field(s: str, f: str) -> Any: ...
