from typing import Any

from _typeshed import Incomplete

logger: Incomplete
DELETION_ALLOWED_PATHS: Incomplete

class LazyLoad:
    import_path: Incomplete
    def __init__(self, import_path: str) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

def rmdir(path: str) -> bool: ...
def caller_name() -> str: ...
def friendly_error(e: Exception, msg: str = "An error occurred.") -> str: ...
def generate_user_id(org: str = "") -> str: ...
def update_hash(hash: str | None = None, s: str = "") -> str: ...
def hash(s: str) -> str: ...
def generate_unique_id() -> str: ...
