name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11  # Replace with your desired Python version

      - name: Install Poetry
        uses: Gr1N/setup-poetry@v8

      - name: Install Poetry dependencies
        run: |
          poetry --version
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          python -m pip install --upgrade pip
          
          poetry install

      - name: Run black
        run: |
          poetry run black --check .

      - name: Install ruff
        uses: chartboost/ruff-action@v1

      - name: Run mypy
        run: |
          poetry run mypy -p langroid

  # Any additional jobs...
